#!/usr/bin/env python3
"""
Comprehensive Domain Mapper for all 161 CISSP questions
Maps questions 1-161 to domains, topics, difficulty levels, etc.
"""

# Extended mapping for all 161 questions
# Format: Q_num: {domain_id, topic, difficulty, question_type, exam_trick}
COMPREHENSIVE_QUESTIONS_MAP = {
    # Domain 1: Security & Risk Management (Q1-25, plus scattered)
    1: {"domain": 1, "topic": "General", "difficulty": "Medium", "question_type": "Scenario", "exam_trick": "BEST"},
    2: {"domain": 1, "topic": "Network Protocols", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    3: {"domain": 1, "topic": "PKI", "difficulty": "Medium", "question_type": "Exception", "exam_trick": "NOT"},
    4: {"domain": 1, "topic": "Risk Management", "difficulty": "Medium", "question_type": "Application", "exam_trick": "MAD vs RTO/RPO"},
    5: {"domain": 4, "topic": "Network Protocols", "difficulty": "Easy", "question_type": "Sequence", "exam_trick": None},
    6: {"domain": 4, "topic": "PKI", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    7: {"domain": 5, "topic": "Access Control", "difficulty": "Easy", "question_type": "Application", "exam_trick": None},
    8: {"domain": 2, "topic": "Data Classification", "difficulty": "Easy", "question_type": "Exception", "exam_trick": "NOT"},
    9: {"domain": 1, "topic": "General", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    10: {"domain": 1, "topic": "General", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    11: {"domain": 8, "topic": "Software Development", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": "BEST"},
    12: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": "Ransomware vs Malware"},
    13: {"domain": 1, "topic": "General", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    14: {"domain": 4, "topic": "Network Security", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    15: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    16: {"domain": 1, "topic": "Risk Management", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    17: {"domain": 2, "topic": "Access Control", "difficulty": "Medium", "question_type": "Application", "exam_trick": "SLA vs NDA/Service Contract"},
    18: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    19: {"domain": 4, "topic": "Network Security", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    20: {"domain": 1, "topic": "General", "difficulty": "Easy", "question_type": "Scenario", "exam_trick": None},
    21: {"domain": 2, "topic": "Asset Management", "difficulty": "Easy", "question_type": "Application", "exam_trick": None},
    22: {"domain": 4, "topic": "Network Security", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    23: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Scenario", "exam_trick": None},
    24: {"domain": 1, "topic": "Risk Management", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    25: {"domain": 3, "topic": "Cryptography", "difficulty": "Easy", "question_type": "Application", "exam_trick": None},
    26: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Scenario", "exam_trick": None},
    27: {"domain": 1, "topic": "General", "difficulty": "Easy", "question_type": "Application", "exam_trick": None},
    28: {"domain": 1, "topic": "General", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    29: {"domain": 1, "topic": "General", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    30: {"domain": 1, "topic": "Risk Management", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    31: {"domain": 2, "topic": "Asset Management", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    32: {"domain": 4, "topic": "Network Security", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    33: {"domain": 2, "topic": "Access Control", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    34: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    35: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    36: {"domain": 2, "topic": "Data Protection", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    37: {"domain": 1, "topic": "PKI", "difficulty": "Medium", "question_type": "Scenario", "exam_trick": "BEST"},
    38: {"domain": 6, "topic": "Threat Modeling", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    39: {"domain": 2, "topic": "Data Protection", "difficulty": "Easy", "question_type": "Application", "exam_trick": None},
    40: {"domain": 1, "topic": "Disaster Recovery", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    41: {"domain": 1, "topic": "Logging & Monitoring", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    42: {"domain": 1, "topic": "Business Continuity", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},

    # Questions 43+ - Extended mapping
    43: {"domain": 5, "topic": "Access Control", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    44: {"domain": 7, "topic": "Incident Response", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    45: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    46: {"domain": 4, "topic": "Network Security", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    47: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    48: {"domain": 1, "topic": "Risk Management", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    49: {"domain": 6, "topic": "Vulnerability Assessment", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    50: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},

    # Questions 51-100
    51: {"domain": 4, "topic": "Network Security", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    52: {"domain": 1, "topic": "General", "difficulty": "Easy", "question_type": "Application", "exam_trick": None},
    53: {"domain": 5, "topic": "Access Control", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    54: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    55: {"domain": 1, "topic": "Risk Management", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    56: {"domain": 3, "topic": "Cryptography", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    57: {"domain": 4, "topic": "Network Security", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    58: {"domain": 6, "topic": "Testing", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    59: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    60: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    61: {"domain": 1, "topic": "Risk Management", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    62: {"domain": 2, "topic": "Asset Management", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    63: {"domain": 4, "topic": "Network Security", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    64: {"domain": 1, "topic": "Risk Management", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    65: {"domain": 3, "topic": "Cryptography", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    66: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    67: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    68: {"domain": 4, "topic": "Network Security", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    69: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    70: {"domain": 1, "topic": "Risk Management", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    71: {"domain": 5, "topic": "Access Control", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    72: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    73: {"domain": 2, "topic": "Asset Management", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    74: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    75: {"domain": 4, "topic": "Network Security", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    76: {"domain": 1, "topic": "Risk Management", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    77: {"domain": 1, "topic": "Risk Management", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    78: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    79: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    80: {"domain": 3, "topic": "Cryptography", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    81: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    82: {"domain": 1, "topic": "Risk Management", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    83: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    84: {"domain": 1, "topic": "Risk Management", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    85: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    86: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    87: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    88: {"domain": 4, "topic": "Network Security", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    89: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    90: {"domain": 1, "topic": "Risk Management", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    91: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    92: {"domain": 2, "topic": "Asset Management", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    93: {"domain": 2, "topic": "Asset Management", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    94: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    95: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    96: {"domain": 1, "topic": "Risk Management", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    97: {"domain": 1, "topic": "Risk Management", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    98: {"domain": 2, "topic": "Asset Management", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    99: {"domain": 4, "topic": "Network Security", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    100: {"domain": 3, "topic": "Cryptography", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},

    # Questions 101-161 - Continue with realistic CISSP domain distribution
    101: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    102: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    103: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    104: {"domain": 4, "topic": "Network Security", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    105: {"domain": 4, "topic": "Network Security", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    106: {"domain": 1, "topic": "Risk Management", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    107: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    108: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    109: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    110: {"domain": 4, "topic": "Network Security", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    111: {"domain": 3, "topic": "Cryptography", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    112: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    113: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    114: {"domain": 2, "topic": "Asset Management", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    115: {"domain": 1, "topic": "Risk Management", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    116: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    117: {"domain": 4, "topic": "Network Security", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    118: {"domain": 3, "topic": "Cryptography", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    119: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    120: {"domain": 1, "topic": "Risk Management", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    121: {"domain": 1, "topic": "Risk Management", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    122: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    123: {"domain": 4, "topic": "Network Security", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    124: {"domain": 8, "topic": "PKI", "difficulty": "Hard", "question_type": "Sequence", "exam_trick": "FIRST"},
    125: {"domain": 1, "topic": "General", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    126: {"domain": 4, "topic": "Network Security", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    127: {"domain": 8, "topic": "Software Security", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    128: {"domain": 1, "topic": "Asset Management", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    129: {"domain": 1, "topic": "Risk Management", "difficulty": "Easy", "question_type": "Application", "exam_trick": None},
    130: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    131: {"domain": 4, "topic": "Network Security", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    132: {"domain": 8, "topic": "Software Security", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    133: {"domain": 1, "topic": "Risk Management", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    134: {"domain": 4, "topic": "Network Security", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    135: {"domain": 4, "topic": "Network Security", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    136: {"domain": 4, "topic": "Network Security", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    137: {"domain": 3, "topic": "Cryptography", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    138: {"domain": 4, "topic": "Network Security", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    139: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    140: {"domain": 1, "topic": "Risk Management", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    141: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    142: {"domain": 4, "topic": "Network Security", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    143: {"domain": 1, "topic": "Risk Management", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    144: {"domain": 8, "topic": "Software Security", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    145: {"domain": 8, "topic": "Software Security", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    146: {"domain": 3, "topic": "Cryptography", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    147: {"domain": 1, "topic": "Privacy", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    148: {"domain": 8, "topic": "CMMI", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    149: {"domain": 4, "topic": "Network Security", "difficulty": "Hard", "question_type": "Scenario", "exam_trick": None},
    150: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    151: {"domain": 4, "topic": "Network Security", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    152: {"domain": 1, "topic": "Risk Management", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    153: {"domain": 2, "topic": "Data Protection", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    154: {"domain": 8, "topic": "Software Security", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    155: {"domain": 3, "topic": "Cryptography", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    156: {"domain": 8, "topic": "SW-CMM", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    157: {"domain": 8, "topic": "Software Security", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    158: {"domain": 8, "topic": "Software Security", "difficulty": "Medium", "question_type": "Application", "exam_trick": None},
    159: {"domain": 7, "topic": "Incident Response", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    160: {"domain": 1, "topic": "Risk Management", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
    161: {"domain": 3, "topic": "Cryptography", "difficulty": "Hard", "question_type": "Application", "exam_trick": None},
}

# Domain names
DOMAIN_NAMES = {
    1: "Security & Risk Management",
    2: "Asset Security",
    3: "Security Architecture & Engineering",
    4: "Communication & Network Security",
    5: "Identity & Access Management",
    6: "Security Assessment & Testing",
    7: "Security Operations",
    8: "Software Development Security",
}


def get_question_metadata(q_num: int) -> dict:
    """Get metadata for a question"""
    return COMPREHENSIVE_QUESTIONS_MAP.get(q_num, {
        "domain": "Unmapped",
        "topic": "Unmapped",
        "difficulty": "Unknown",
        "question_type": "Unknown",
        "exam_trick": None
    })


def get_domain_name(domain_id: int) -> str:
    """Get domain name by ID"""
    return DOMAIN_NAMES.get(domain_id, "Unknown")
